version: '3.7'
services:
  todolist_api:
    tty: true
    container_name: todolist_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - backend
    depends_on:
      - todolist_db
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    command: ["./wait-for-it.sh", "todolist-db:5432", "--", "npm" ,"run", "start:debug"]
# If your on Windows uncomment line below and comment line above.
#    command: ["npm" ,"run", "start:debug"]
    restart: on-failure

  todolist_db:
    image: postgres
    container_name: "todolist_db"
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  db:
    name: db-volume
networks:
  backend:
    driver: "bridge"
